usethis::use_testthat(3)
usethis::use_test("f_lrpower")
usethis::use_test("f_lrsamplesize")
usethis::use_vignette("fixed_follow-up")
usethis::use_vignette("group_sequential_simulation")
usethis::use_vignette("lakatos_schoenfeld")
usethis::use_vignette("maxcombo")
usethis::use_vignette("non-proportional_hazards")
usethis::use_vignette("stratified")

install.packages("installr")
library(installr)
install.pandoc()
