#include <Rcpp.h>
#include <R_ext/Applic.h>

using namespace Rcpp;

#ifndef __SURVIVAL_ANALYSIS__
#define __SURVIVAL_ANALYSIS__

DataFrame survQuantile(const NumericVector& time,
                       const IntegerVector& event,
                       const double cilevel,
                       const std::string transform,
                       const NumericVector& probs);

DataFrame kmest(const DataFrame data,
                const StringVector& rep,
                const StringVector& stratum,
                const std::string time,
                const std::string time2,
                const std::string event,
                const std::string weight,
                const std::string conftype,
                const double conflev,
                const bool keep_censor);

DataFrame kmdiff(const DataFrame data,
                 const StringVector& rep,
                 const StringVector& stratum,
                 const std::string treat,
                 const std::string time,
                 const std::string event,
                 const double milestone,
                 const double survDiffH0,
                 const double conflev);

DataFrame lrtest(const DataFrame data,
                 const StringVector& rep,
                 const StringVector& stratum,
                 const std::string treat,
                 const std::string time,
                 const std::string time2,
                 const std::string event,
                 const std::string weight,
                 const bool weight_readj,
                 const double rho1,
                 const double rho2);

DataFrame rmest(const DataFrame data,
                const StringVector& rep,
                const StringVector& stratum,
                const std::string time,
                const std::string event,
                const double milestone,
                const double conflev,
                const bool biascorrection);

DataFrame rmdiff(const DataFrame data,
                 const StringVector& rep,
                 const StringVector& stratum,
                 const std::string treat,
                 const std::string time,
                 const std::string event,
                 const double milestone,
                 const double rmstDiffH0,
                 const double conflev,
                 const bool biascorrection);

List liferegcpp(const DataFrame data,
                const StringVector& rep,
                const StringVector& stratum,
                const std::string time,
                const std::string time2,
                const std::string event,
                const StringVector& covariates,
                const std::string weight,
                const std::string offset,
                const std::string id,
                const std::string dist,
                const NumericVector& init,
                const bool robust,
                const bool plci,
                const double alpha,
                const int maxiter,
                const double eps);

NumericMatrix residuals_liferegcpp(const NumericVector& beta,
                                   const NumericMatrix& vbeta,
                                   DataFrame data,
                                   const StringVector& stratum,
                                   const std::string time,
                                   const std::string time2,
                                   const std::string event,
                                   const StringVector& covariates,
                                   const std::string weight,
                                   const std::string offset,
                                   const std::string id,
                                   const std::string dist,
                                   const std::string type,
                                   const bool collapse,
                                   const bool weighted);

List phregcpp(const DataFrame data,
              const StringVector& rep,
              const StringVector& stratum,
              const std::string time,
              const std::string time2,
              const std::string event,
              const StringVector& covariates,
              const std::string weight,
              const std::string offset,
              const std::string id,
              const std::string ties,
              const NumericVector& init,
              const bool robust,
              const bool est_basehaz,
              const bool est_resid,
              const bool firth,
              const bool plci,
              const double alpha,
              const int maxiter,
              const double eps);

DataFrame survfit_phregcpp(const int p,
                           const NumericVector& beta,
                           const NumericMatrix& vbeta,
                           DataFrame basehaz,
                           DataFrame newdata,
                           const StringVector& covariates,
                           const StringVector& stratum,
                           const std::string offset,
                           const std::string id,
                           const std::string tstart,
                           const std::string tstop,
                           const bool sefit,
                           const String conftype,
                           const double conflev);

List residuals_phregcpp(const int p,
                        const NumericVector& beta,
                        const NumericMatrix& vbeta,
                        const NumericVector& resmart,
                        DataFrame data,
                        const StringVector& stratum,
                        const std::string time,
                        const std::string time2,
                        const std::string event,
                        const StringVector& covariates,
                        const std::string weight,
                        const std::string offset,
                        const std::string id,
                        const std::string ties,
                        const std::string type,
                        const bool collapse,
                        const bool weighted);

List assess_phregcpp(const int p,
                     const NumericVector& beta,
                     const NumericMatrix& vbeta,
                     DataFrame data,
                     const StringVector& stratum,
                     const std::string time,
                     const std::string time2,
                     const std::string event,
                     const StringVector& covariates,
                     const std::string weight,
                     const std::string offset,
                     const std::string ties,
                     const int resample,
                     const int seed);

List zph_phregcpp(const int p,
                  const NumericVector& beta,
                  const NumericMatrix& vbeta,
                  const NumericVector& resmart,
                  DataFrame data,
                  const StringVector& stratum,
                  const std::string time,
                  const std::string time2,
                  const std::string event,
                  const StringVector& covariates,
                  const std::string weight,
                  const std::string offset,
                  const std::string ties,
                  const std::string transform);

#endif // __SURVIVAL_ANALYSIS__
